/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCenterUpdateDTOCenterType } from './healthCenterUpdateDTOCenterType';

export interface HealthCenterUpdateDTO {
  /** @minLength 1 */
  name: string;
  centerType: HealthCenterUpdateDTOCenterType;
  locationId?: string;
  totalFamilies?: number;
  totalPopulation?: number;
}
