/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCenterCreateDTOCenterType } from './healthCenterCreateDTOCenterType';

export interface HealthCenterCreateDTO {
  /** @minLength 1 */
  name: string;
  centerType: HealthCenterCreateDTOCenterType;
  locationId: string;
  totalFamilies?: number;
  totalPopulation?: number;
}
