/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocationFilterDTOType } from './locationFilterDTOType';

export interface LocationFilterDTO {
  type?: LocationFilterDTOType;
  pincode?: string;
  subdistrict?: string;
  district?: string;
  state?: string;
  country?: string;
}
