/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocationResponseDTOType } from './locationResponseDTOType';

export interface LocationResponseDTO {
  id?: string;
  name?: string;
  type?: LocationResponseDTOType;
  pincode?: string;
  subdistrict?: string;
  district?: string;
  state?: string;
  country?: string;
  createdAt?: string;
  updatedAt?: string;
}
