/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetAgeDistribution200,
  GetAgeDistributionParams,
  GetAliveStatusDistribution200,
  GetAliveStatusDistributionParams,
  GetGenderDistribution200,
  GetGenderDistributionParams,
  GetPovertyDistribution200,
  GetPovertyDistributionParams,
  GetRoleDistribution200,
  GetRoleDistributionParams
} from '../../model/analyticsService';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AnalyticsService {
  constructor(
    private http: HttpClient,
  ) {} getRoleDistribution<TData = GetRoleDistribution200>(
    params: GetRoleDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getRoleDistribution<TData = GetRoleDistribution200>(
    params: GetRoleDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getRoleDistribution<TData = GetRoleDistribution200>(
    params: GetRoleDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getRoleDistribution<TData = GetRoleDistribution200>(
    params: GetRoleDistributionParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/analytics/roles`,{
    ...options,
        params: {...params.analyticsFilterDTO, ...options?.params},}
    );
  }
 getPovertyDistribution<TData = GetPovertyDistribution200>(
    params: GetPovertyDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getPovertyDistribution<TData = GetPovertyDistribution200>(
    params: GetPovertyDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getPovertyDistribution<TData = GetPovertyDistribution200>(
    params: GetPovertyDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getPovertyDistribution<TData = GetPovertyDistribution200>(
    params: GetPovertyDistributionParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/analytics/poverty`,{
    ...options,
        params: {...params.analyticsFilterDTO, ...options?.params},}
    );
  }
 getGenderDistribution<TData = GetGenderDistribution200>(
    params: GetGenderDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getGenderDistribution<TData = GetGenderDistribution200>(
    params: GetGenderDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getGenderDistribution<TData = GetGenderDistribution200>(
    params: GetGenderDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getGenderDistribution<TData = GetGenderDistribution200>(
    params: GetGenderDistributionParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/analytics/gender`,{
    ...options,
        params: {...params.analyticsFilterDTO, ...options?.params},}
    );
  }
 getAliveStatusDistribution<TData = GetAliveStatusDistribution200>(
    params: GetAliveStatusDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAliveStatusDistribution<TData = GetAliveStatusDistribution200>(
    params: GetAliveStatusDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAliveStatusDistribution<TData = GetAliveStatusDistribution200>(
    params: GetAliveStatusDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAliveStatusDistribution<TData = GetAliveStatusDistribution200>(
    params: GetAliveStatusDistributionParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/analytics/alive`,{
    ...options,
        params: {...params.analyticsFilterDTO, ...options?.params},}
    );
  }
 getAgeDistribution<TData = GetAgeDistribution200>(
    params: GetAgeDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAgeDistribution<TData = GetAgeDistribution200>(
    params: GetAgeDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAgeDistribution<TData = GetAgeDistribution200>(
    params: GetAgeDistributionParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAgeDistribution<TData = GetAgeDistribution200>(
    params: GetAgeDistributionParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/analytics/age`,{
    ...options,
        params: {...params.analyticsFilterDTO, ...options?.params},}
    );
  }
};

export type GetRoleDistributionClientResult = NonNullable<GetRoleDistribution200>
export type GetPovertyDistributionClientResult = NonNullable<GetPovertyDistribution200>
export type GetGenderDistributionClientResult = NonNullable<GetGenderDistribution200>
export type GetAliveStatusDistributionClientResult = NonNullable<GetAliveStatusDistribution200>
export type GetAgeDistributionClientResult = NonNullable<GetAgeDistribution200>
