server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes: 
# Docs Routes
        - id: auth-docs
          uri: lb://AUTH-SERVICE
          predicates:
          - Path=/auth/v3/api-docs
          filters:
          - RewritePath=/auth/v3/api-docs, /v3/api-docs

        - id: asha-docs
          uri: lb://ASHA-SERVICE
          predicates:
          - Path=/asha/v3/api-docs
          filters:
          - RewritePath=/asha/v3/api-docs, /v3/api-docs

        - id: family-docs
          uri: lb://FAMILY-SERVICE
          predicates:
          - Path=/family/v3/api-docs
          filters:
          - RewritePath=/family/v3/api-docs, /v3/api-docs

        - id: vaccination-docs
          uri: lb://VACCINATION-SERVICE
          predicates:
           - Path=/vaccination/v3/api-docs
          filters:
           - RewritePath=/vaccination/v3/api-docs, /v3/api-docs

        - id: pregnancy-docs
          uri: lb://PREGNANCY-SERVICE
          predicates:
           - Path=/pregnancy/v3/api-docs
          filters:
           - RewritePath=/pregnancy/v3/api-docs, /v3/api-docs


# Service Routes
        - id: auth-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: users-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtGatewayAuthenticationFilter

        - id: family-route
          uri: lb://FAMILY-SERVICE
          predicates:
            - Path=/family/**
          filters:
            - JwtGatewayAuthenticationFilter

        - id: asha-route
          uri: lb://ASHA-SERVICE
          predicates:
          - Path=/asha/**
          filters:
          - JwtGatewayAuthenticationFilter

        - id: pregnancy-route
          uri: lb://PREGNANCY-SERVICE
          predicates:
          - Path=/pregnancy/**
          filters:
          - JwtGatewayAuthenticationFilter


eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    urls:
    - name: Auth Service
      url: /auth/v3/api-docs
    - name: Asha Service
      url: /asha/v3/api-docs
    - name: Family Service
      url: /family/v3/api-docs
    - name: Vaccination Service
      url: /vaccination/v3/api-docs
    - name: Pregnancy Service
      url: /pregnancy/v3/api-docs