server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: auth-no-filter
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /auth/${segment}

        - id: users-with-filter
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /users/${segment}
            - JwtAuthenticationFilter

        - id: family-route
          uri: lb://FAMILY-SERVICE
          predicates:
            - Path=/api/v1/family/**
          filters:
            - RewritePath=/api/v1/family/(?<segment>.*), /family/${segment}
            - JwtAuthenticationFilter

        - id: swagger-auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/auth/(?<segment>.*), /swagger-ui/${segment}

        - id: api-docs-auth
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - SetPath=/v3/api-docs

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
