/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { RoleRequestResponseDTO } from './roleRequestResponseDTO';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelRoleRequestResponseDTO {
  content?: RoleRequestResponseDTO[];
  page?: PageMetadata;
}
