/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';

export interface UserUpdateDTO {
  id: string;
  name?: Name;
  healthCenterId: string;
  /**
   * @minLength 12
   * @maxLength 12
   */
  adharNumber?: string;
}
