/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { UserResponseDTORolesItem } from './userResponseDTORolesItem';

export interface UserResponseDTO {
  id?: string;
  name?: Name;
  healthCenterId?: string;
  adharNumber?: string;
  roles?: UserResponseDTORolesItem[];
  createdAt?: string;
  updatedAt?: string;
}
