/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { ApiError } from './apiError';

export interface ValidationErrorResponse {
  success?: boolean;
  status?: number;
  error?: string;
  message?: string;
  path?: string;
  errors?: ApiError[];
  timestamp?: string;
}
