/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GenerateFamilyReportParams,
  GenerateHealthRecordsReportParams,
  GenerateMemberReportParams
} from '../../model/analyticsService';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class ReportsService {
  constructor(
    private http: HttpClient,
  ) {} generateMemberReport<TData = Blob>(
    params: GenerateMemberReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    generateMemberReport<TData = Blob>(
    params: GenerateMemberReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    generateMemberReport<TData = Blob>(
    params: GenerateMemberReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;generateMemberReport<TData = Blob>(
    params: GenerateMemberReportParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/reports/member`,{
    ...options,
        params: {ashaId : params.ashaId, ...options?.params},}
    );
  }
 generateHealthRecordsReport<TData = Blob>(
    params: GenerateHealthRecordsReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    generateHealthRecordsReport<TData = Blob>(
    params: GenerateHealthRecordsReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    generateHealthRecordsReport<TData = Blob>(
    params: GenerateHealthRecordsReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;generateHealthRecordsReport<TData = Blob>(
    params: GenerateHealthRecordsReportParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/reports/health`,{
    ...options,
        params: {ashaId : params.ashaId, ...options?.params},}
    );
  }
 generateFamilyReport<TData = Blob>(
    params: GenerateFamilyReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    generateFamilyReport<TData = Blob>(
    params: GenerateFamilyReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    generateFamilyReport<TData = Blob>(
    params: GenerateFamilyReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;generateFamilyReport<TData = Blob>(
    params: GenerateFamilyReportParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:8080/reports/family`,{
    ...options,
        params: {ashaId : params.ashaId, ...options?.params},}
    );
  }
};

export type GenerateMemberReportClientResult = NonNullable<Blob>
export type GenerateHealthRecordsReportClientResult = NonNullable<Blob>
export type GenerateFamilyReportClientResult = NonNullable<Blob>
