/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { AgeGroupCountAgeGroup } from './ageGroupCountAgeGroup';

export interface AgeGroupCount {
  id?: string;
  ashaId?: string;
  ageGroup?: AgeGroupCountAgeGroup;
  count?: number;
  createdAt?: string;
}
