/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type AgeGroupCountAgeGroup = typeof AgeGroupCountAgeGroup[keyof typeof AgeGroupCountAgeGroup];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgeGroupCountAgeGroup = {
  INFANT: 'INFANT',
  CHILD: 'CHILD',
  TEEN: 'TEEN',
  ADULT: 'ADULT',
  MID_AGED_ADULT: 'MID_AGED_ADULT',
  SENIOR: 'SENIOR',
  UNKNOWN: 'UNKNOWN',
} as const;
