/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { AliveStatusCountAliveStatus } from './aliveStatusCountAliveStatus';

export interface AliveStatusCount {
  id?: string;
  ashaId?: string;
  aliveStatus?: AliveStatusCountAliveStatus;
  count?: number;
  createdAt?: string;
}
