/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type AliveStatusCountAliveStatus = typeof AliveStatusCountAliveStatus[keyof typeof AliveStatusCountAliveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AliveStatusCountAliveStatus = {
  aliveStatus: 'ALIVE',
  DECEASED: 'DECEASED',
  UNKNOWN: 'UNKNOWN',
} as const;
