/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface AnalyticsFilterDTO {
  userId?: string;
  start?: string;
  end?: string;
}
