/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type GenderCountGender = typeof GenderCountGender[keyof typeof GenderCountGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenderCountGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
