/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { AgeGroupCount } from './ageGroupCount';

export type GetAgeDistribution200 = {[key: string]: AgeGroupCount[]};
