/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface NcdCount {
  id?: string;
  ashaId?: string;
  ncdName?: string;
  count?: number;
  createdAt?: string;
}
