/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type PovertyStatusCountPovertyStatus = typeof PovertyStatusCountPovertyStatus[keyof typeof PovertyStatusCountPovertyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PovertyStatusCountPovertyStatus = {
  APL: 'APL',
  BPL: 'BPL',
} as const;
