/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { RoleRequestStatusCountStatus } from './roleRequestStatusCountStatus';

export interface RoleRequestStatusCount {
  id?: string;
  status?: RoleRequestStatusCountStatus;
  count?: number;
  createdAt?: string;
}
