/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type FamilyDataResponseDTOPovertyStatus = typeof FamilyDataResponseDTOPovertyStatus[keyof typeof FamilyDataResponseDTOPovertyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyDataResponseDTOPovertyStatus = {
  APL: 'APL',
  BPL: 'BPL',
} as const;
