/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyStatsPovertyStats } from './familyStatsPovertyStats';

export interface FamilyStats {
  totalFamilies?: number;
  povertyStats?: FamilyStatsPovertyStats;
}
