/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA ANALYTICS-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberStatsGenderDistribution } from './memberStatsGenderDistribution';
import type { MemberStatsAgeDistribution } from './memberStatsAgeDistribution';

export interface MemberStats {
  totalMembers?: number;
  averageMembersPerFamily?: number;
  genderDistribution?: MemberStatsGenderDistribution;
  ageDistribution?: MemberStatsAgeDistribution;
}
