/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCenterResponseDTO } from './healthCenterResponseDTO';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface HealthCenterPageResponseDTO {
  content?: HealthCenterResponseDTO[];
  pageable?: PageableObject;
  totalPages?: number;
  totalElements?: number;
  last?: boolean;
  size?: number;
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  first?: boolean;
  empty?: boolean;
}
