/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type HealthCenterResponseDTOCenterType = typeof HealthCenterResponseDTOCenterType[keyof typeof HealthCenterResponseDTOCenterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCenterResponseDTOCenterType = {
  SUB_CENTER: 'SUB_CENTER',
  PRIMARY_HEALTH_CENTER: 'PRIMARY_HEALTH_CENTER',
  COMMUNITY_HEALTH_CENTER: 'COMMUNITY_HEALTH_CENTER',
  SUB_DISTRICT_HOSPITAL: 'SUB_DISTRICT_HOSPITAL',
  DISTRICT_HOSPITAL: 'DISTRICT_HOSPITAL',
  MEDICAL_COLLEGE: 'MEDICAL_COLLEGE',
} as const;
