/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCenterResponseDTOCenterType } from './healthCenterResponseDTOCenterType';

export interface HealthCenterResponseDTO {
  id?: string;
  name?: string;
  centerType?: HealthCenterResponseDTOCenterType;
  locationId?: string;
  totalFamilies?: number;
  totalPopulation?: number;
  createdAt?: string;
  updatedAt?: string;
}
