/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type LocationCreateDTOType = typeof LocationCreateDTOType[keyof typeof LocationCreateDTOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationCreateDTOType = {
  CITY: 'CITY',
  VILLAGE: 'VILLAGE',
  TOWN: 'TOWN',
  HAMLET: 'HAMLET',
} as const;
