/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type LocationResponseDTOType = typeof LocationResponseDTOType[keyof typeof LocationResponseDTOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationResponseDTOType = {
  City: 'City',
  Village: 'Village',
  Town: 'Town',
  Hamlet: 'Hamlet',
} as const;
