/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface NCDCreateDTO {
  /** @minLength 1 */
  name: string;
  description?: string;
}
