/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { NCDResponseDTO } from './nCDResponseDTO';
import { PageInfo } from '../PageInfo';

export interface NCDPageResponseDTO {
  content?: NCDResponseDTO[];
  page : PageInfo;
}
