/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface Name {
  /**
   * @minLength 2
   * @maxLength 100
   */
  firstname: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  middlename?: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  lastname: string;
  fullName?: string;
}
