/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import { PageInfo } from '../PageInfo';
import type { RoleRequestResponseDTO } from './roleRequestResponseDTO';

export interface RoleRequestPageResponseDTO {
  content?: RoleRequestResponseDTO[];
  page?: PageInfo;
}
