/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { RoleRequestUpdateDTORole } from './roleRequestUpdateDTORole';

export interface RoleRequestUpdateDTO {
  name?: Name;
  role: RoleRequestUpdateDTORole;
  healthCenter: string;
}
