/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { RoleRequestResponseDTORole } from './roleRequestResponseDTORole';
import type { RoleRequestResponseDTOStatus } from './roleRequestResponseDTOStatus';

export interface RoleRequestResponseDTO {
  id?: string;
  name?: Name;
  role?: RoleRequestResponseDTORole;
  userId?: string;
  status?: RoleRequestResponseDTOStatus;
  healthCenter?: string;
  createdAt?: string;
  updatedAt?: string;
}
