/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}
