/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDTO } from './userResponseDTO';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface UserPageResponseDTO {
  content?: UserResponseDTO[];
  pageable?: PageableObject;
  totalPages?: number;
  totalElements?: number;
  last?: boolean;
  size?: number;
  number?: number;
  sort?: SortObject;
  first?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}
