/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import { PageInfo } from '../PageInfo';
import type { UserResponseDTO } from './userResponseDTO';

export interface UserPageResponseDTO {
  content?: UserResponseDTO[];
  page?:PageInfo;
}
