/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocationFilterDTO } from './locationFilterDTO';
import type { Pageable } from './pageable';

export type GetAllLocationsParams = {
filterDTO: LocationFilterDTO;
pageable: Pageable;
};
