/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { RoleRequestFilterDTO } from './roleRequestFilterDTO';
import type { Pageable } from './pageable';

export type GetAllRoleRequestsParams = {
filterDTO: RoleRequestFilterDTO;
pageable: Pageable;
};
