/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocationFilterDTO } from './locationFilterDTO';

export type GetTotalCountParams = {
filterDTO: LocationFilterDTO;
};
