/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { UserFilterDTO } from './userFilterDTO';

export type GetTotalUsersParams = {
filterDTO: UserFilterDTO;
};
