/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type HealthCenterFilterDTOCenterType = typeof HealthCenterFilterDTOCenterType[keyof typeof HealthCenterFilterDTOCenterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCenterFilterDTOCenterType = {
  Subcenter: 'Subcenter',
  Primary_Health_Center: 'Primary Health Center',
  Community_Health_Center: 'Community Health Center',
  'Sub-district_Hospital': 'Sub-district Hospital',
  District_Hospital: 'District Hospital',
  Medical_College: 'Medical College',
} as const;
