/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA MASTERDATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocationCreateDTOType } from './locationCreateDTOType';

export interface LocationCreateDTO {
  /** @minLength 1 */
  name: string;
  type: LocationCreateDTOType;
  /** @minLength 1 */
  pincode: string;
  /** @minLength 1 */
  subdistrict: string;
  /** @minLength 1 */
  district: string;
  /** @minLength 1 */
  state: string;
  /** @minLength 1 */
  country: string;
}
