/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { MemberDataResponseDTOGender } from './memberDataResponseDTOGender';

export interface MemberDataResponseDTO {
  id?: string;
  familyId?: string;
  ashaId?: string;
  name?: Name;
  gender?: MemberDataResponseDTOGender;
  dateOfBirth?: string;
  birthPlace?: string;
  age?: number;
  adharNumber?: string;
  abhaNumber?: string;
  mobileNumber?: string;
  alive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
