/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type RoleRequestCreateDTORole = typeof RoleRequestCreateDTORole[keyof typeof RoleRequestCreateDTORole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleRequestCreateDTORole = {
  SYSTEM: 'SYSTEM',
  USER: 'USER',
  ADMIN: 'ADMIN',
  ASHA: 'ASHA',
} as const;
