/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { RoleRequestFilterDTORole } from './roleRequestFilterDTORole';
import type { RoleRequestFilterDTOStatus } from './roleRequestFilterDTOStatus';

export interface RoleRequestFilterDTO {
  role?: RoleRequestFilterDTORole;
  status?: RoleRequestFilterDTOStatus;
  healthCenter?: string;
}
