/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type RoleRequestFilterDTORole = typeof RoleRequestFilterDTORole[keyof typeof RoleRequestFilterDTORole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleRequestFilterDTORole = {
  SYSTEM: 'SYSTEM',
  USER: 'USER',
  ADMIN: 'ADMIN',
  ASHA: 'ASHA',
} as const;
