/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA USER-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type RoleRequestFilterDTOStatus = typeof RoleRequestFilterDTOStatus[keyof typeof RoleRequestFilterDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleRequestFilterDTOStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
