/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type FamilyFilterDTOPovertyStatus = typeof FamilyFilterDTOPovertyStatus[keyof typeof FamilyFilterDTOPovertyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyFilterDTOPovertyStatus = {
  APL: 'APL',
  BPL: 'BPL',
} as const;
