/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import { PageInfo } from '../PageInfo';
import type { FamilyDataResponseDTO } from './familyDataResponseDTO';

export interface FamilyPageResponseDTO {
  content?: FamilyDataResponseDTO[];
  page?: PageInfo;
}
