/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyCreateDTO } from './familyCreateDTO';
import type { HeadMemberDTO } from './headMemberDTO';

export interface FamilyRegistrationDTO {
  family?: FamilyCreateDTO;
  headMember?: HeadMemberDTO;
}
