/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyDataResponseDTOPovertyStatus } from './familyDataResponseDTOPovertyStatus';

export interface FamilyDataResponseDTO {
  id?: string;
  headMemberId?: string;
  locationId?: string;
  ashaId?: string;
  povertyStatus?: FamilyDataResponseDTOPovertyStatus;
  createdAt?: string;
  updatedAt?: string;
}
