/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyDataFilterDTOPovertyStatus } from './familyDataFilterDTOPovertyStatus';

export interface FamilyDataFilterDTO {
  ashaId?: string;
  povertyStatus?: FamilyDataFilterDTOPovertyStatus;
  houseId?: number;
}
