/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type FamilyResponseDTOPovertyStatus = typeof FamilyResponseDTOPovertyStatus[keyof typeof FamilyResponseDTOPovertyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyResponseDTOPovertyStatus = {
  APL: 'APL',
  BPL: 'BPL',
} as const;
