/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyResponseDTOPovertyStatus } from './familyResponseDTOPovertyStatus';

export interface FamilyResponseDTO {
  id?: string;
  headMemberId?: string;
  ashaId?: string;
  houseId?: number;
  povertyStatus?: FamilyResponseDTOPovertyStatus;
  createdAt?: string;
  updatedAt?: string;
}
