/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyResponseDTO } from './familyResponseDTO';
import { PageInfo } from '../PageInfo';

export interface FamilyPageResponseDTO {
  content?: FamilyResponseDTO[];
  page : PageInfo;
}
