/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyFilterDTO } from './familyFilterDTO';
import type { Pageable } from './pageable';

export type GetFamilyPageParams = {
filterDTO: FamilyFilterDTO;
pageable: Pageable;
};
