/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberFilterDTO } from './memberFilterDTO';
import type { Pageable } from './pageable';

export type GetMemberPageParams = {
filterDTO: MemberFilterDTO;
pageable: Pageable;
};
