/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import { PageInfo } from '../PageInfo';
import type { HealthRecordResponseDTO } from './healthRecordResponseDTO';

export interface HealthRecordPageResponseDTO {
  content?: HealthRecordResponseDTO[];
  page?:PageInfo;
}
