/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { MemberUpdateDTOGender } from './memberUpdateDTOGender';
import type { MemberUpdateDTOAliveStatus } from './memberUpdateDTOAliveStatus';

export interface MemberUpdateDTO {
  familyId: string;
  name?: Name;
  gender: MemberUpdateDTOGender;
  dateOfBirth?: string;
  birthPlace?: string;
  /**
   * @minLength 10
   * @maxLength 12
   */
  adharNumber: string;
  abhaNumber?: string;
  /** @pattern ^[6-9]\d{9}$ */
  mobileNumber?: string;
  aliveStatus?: MemberUpdateDTOAliveStatus;
}
