/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type MemberResponseDTOAliveStatus = typeof MemberResponseDTOAliveStatus[keyof typeof MemberResponseDTOAliveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberResponseDTOAliveStatus = {
  aliveStatus: 'ALIVE',
  DECEASED: 'DECEASED',
  UNKNOWN: 'UNKNOWN',
} as const;
