/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberFilterDTOGender } from './memberFilterDTOGender';
import type { MemberFilterDTOAliveStatus } from './memberFilterDTOAliveStatus';

export interface MemberFilterDTO {
  familyId?: string;
  ashaId?: string;
  gender?: MemberFilterDTOGender;
  dateOfBirth?: string;
  minAge?: number;
  maxAge?: number;
  aliveStatus?: MemberFilterDTOAliveStatus;
}
