/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberResponseDTO } from './memberResponseDTO';
import { PageInfo } from '../PageInfo';

export interface MemberDataPageResponseDTO {
  content?: MemberResponseDTO[];
  page : PageInfo;
}
