/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type MemberFilterDTOAliveStatus = typeof MemberFilterDTOAliveStatus[keyof typeof MemberFilterDTOAliveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberFilterDTOAliveStatus = {
  ALIVE: 'ALIVE',
  DECEASED: 'DECEASED',
  UNKNOWN: 'UNKNOWN',
} as const;
