/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import { PageInfo } from '../PageInfo';
import type { MemberDataResponseDTO } from './memberDataResponseDTO';

export interface MemberDataPageResponseDTO {
  content?: MemberDataResponseDTO[];
  page?: PageInfo;
}
