/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { MemberResponseDTOGender } from './memberResponseDTOGender';
import type { MemberResponseDTOAliveStatus } from './memberResponseDTOAliveStatus';

export interface MemberResponseDTO {
  id?: string;
  familyId?: string;
  ashaId?: string;
  name?: Name;
  gender?: MemberResponseDTOGender;
  dateOfBirth?: string;
  birthPlace?: string;
  age?: number;
  adharNumber?: string;
  abhaNumber?: string;
  mobileNumber?: string;
  aliveStatus?: MemberResponseDTOAliveStatus;
  createdAt?: string;
  updatedAt?: string;
}
