/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { SortObject } from './sortObject';

export interface PageableObject {
  paged?: boolean;
  number?: number;
  size?: number;
  unpaged?: boolean;
  totalElements: number;
  totalPages: number;
}
