/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  success?: boolean;
  status?: number;
  error?: string;
  message?: string;
  path?: string;
  timestamp?: string;
}
