/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type FamilyCreateDTOPovertyStatus = typeof FamilyCreateDTOPovertyStatus[keyof typeof FamilyCreateDTOPovertyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyCreateDTOPovertyStatus = {
  APL: 'APL',
  BPL: 'BPL',
} as const;
