/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyCreateDTOPovertyStatus } from './familyCreateDTOPovertyStatus';

export interface FamilyCreateDTO {
  locationId: string;
  ashaId: string;
  povertyStatus: FamilyCreateDTOPovertyStatus;
}
