/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyDataFilterDTO } from './familyDataFilterDTO';
import type { Pageable } from './pageable';

export type GetAllFamiliesParams = {
filterDTO: FamilyDataFilterDTO;
pageable: Pageable;
};
