/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */

export type MemberUpdateDTOGender = typeof MemberUpdateDTOGender[keyof typeof MemberUpdateDTOGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberUpdateDTOGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
