/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberDataFilterDTOGender } from './memberDataFilterDTOGender';

export interface MemberDataFilterDTO {
  familyId?: string;
  ashaId?: string;
  gender?: MemberDataFilterDTOGender;
  dateOfBirth?: string;
  age?: number;
  alive?: boolean;
}
