/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { Name } from './name';
import type { MemberCreateDTOGender } from './memberCreateDTOGender';

export interface MemberCreateDTO {
  familyId: string;
  ashaId: string;
  name?: Name;
  gender: MemberCreateDTOGender;
  dateOfBirth?: string;
  birthPlace?: string;
  /**
   * @minLength 10
   * @maxLength 12
   */
  adharNumber: string;
  abhaNumber?: string;
  /** @pattern ^[6-9]\d{9}$ */
  mobileNumber?: string;
}
