/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { MemberDataResponseDTO } from './memberDataResponseDTO';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelMemberDataResponseDTO {
  content?: MemberDataResponseDTO[];
  page?: PageMetadata;
}
