/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * ADRASHA DATA-SERVICE API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { HealthRecordResponseDTO } from './healthRecordResponseDTO';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelHealthRecordResponseDTO {
  content?: HealthRecordResponseDTO[];
  page?: PageMetadata;
}
